---
- block:
  - name: Create temp dir
    tempfile:
      state: directory
    register: tmp

  - name: Copy app to temp
    copy:
      src: "{{ root_dir }}/../apps/cluster-tool/{{ item }}"
      dest: "{{ tmp.path }}/{{ item }}"
    loop:
      - main.py
      - k8s.py
      - utils.py
      - vault.py
      - requirements.txt
      - Dockerfile
      - VERSION

  - name: Set fact with image path
    set_fact:
      image_path: "{{ tmp.path }}/tool.tar"

  - name: Create image
    docker_image:
      source: build
      archive_path: "{{ image_path }}"
      build:
        path: "{{ tmp.path }}"
        pull: no
      tag: "{{ lookup('file', root_dir + '/../apps/cluster-tool/VERSION') }}"
      name: cluster-tool
  when: inventory_hostname == 'master1'

- name: Download image to controller
  fetch:
    src: "{{ image_path }}"
    dest: /tmp
    force: yes
  when: inventory_hostname == 'master1'

- name: Copy file to node
  copy:
    src: /tmp/master1/{{ hostvars[groups['master'][0]]['image_path'] }}
    dest: /tmp/tool.tar
    force: yes
  when: inventory_hostname != 'master1'

- name: Import image
  become: yes
  command: k3s ctr image import {{ image_path if inventory_hostname == 'master1' else '/tmp/tool.tar' }}
