---
cluster_user: tposse
cluster_domain: tiagoposse.com
kubeconfig: ~/.kube/config
versions:
  k3s: v1.18.10+k3s1

root_dir: "{{ playbook_dir | regex_replace('/playbooks.*', '') }}"
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"