---
- block:
  - name: Create temp dir
    tempfile:
      state: directory
    register: tmp

  - name: Copy Dockerfile to temp
    copy:
      src: Dockerfile
      dest: "{{ tmp.path }}/Dockerfile"

  - name: Set fact with image path
    set_fact:
      image_path: "{{ tmp.path }}/agent.tar"

  - name: Create image
    docker_image:
      source: build
      archive_path: "{{ image_path }}"
      build:
        path: "{{ tmp.path }}"
        pull: yes
      tag: local
      name: vault-agent
  when: inventory_hostname == 'master1'

- name: Download image to controller
  fetch:
    src: "{{ image_path }}"
    dest: /tmp
    force: yes
  when: inventory_hostname == 'master1'

- name: Copy file to node
  copy:
    src: /tmp/master1/{{ hostvars[groups['master'][0]]['image_path'] }}
    dest: /tmp/agent.tar
    force: yes
  when: inventory_hostname != 'master1'

- name: Import image
  command: k3s ctr image import {{ image_path if inventory_hostname == 'master1' else '/tmp/agent.tar' }}
