---
- block:
  - name: Create temp dir
    tempfile:
      state: directory
    register: tmp

  - name: Copy app to temp
    copy:
      src: "{{ root_dir }}/../apps/dyndns/{{ item }}"
      dest: "{{ tmp.path }}/{{ item }}"
    loop:
      - main.py
      - requirements.txt
      - Dockerfile
      - VERSION

  - name: Set fact with image path
    set_fact:
      image_path: "{{ tmp.path }}/dyndns.tar"

  - name: Create image
    docker_image:
      source: build
      archive_path: "{{ image_path }}"
      build:
        path: "{{ tmp.path }}"
        pull: yes
      tag: "{{ lookup('file', root_dir + '/../apps/dyndns/VERSION') }}"
      name: dyndns

  - name: Download image to controller
    fetch:
      src: "{{ image_path }}"
      dest: /tmp
      force: yes
  when: inventory_hostname == 'master1'

- name: Copy file to node
  copy:
    src: /tmp/master1/{{ hostvars[groups['master'][0]]['image_path'] }}
    dest: /tmp/dyndns.tar
    force: yes
  when: inventory_hostname != 'master1'

- name: Import image
  become: yes
  command: k3s ctr image import {{ image_path if inventory_hostname == 'master1' else '/tmp/dyndns.tar' }}